#!/usr/bin/bash

# simple installer script, to build the ansible image and copy some scripts to /usr/local/bin

tag="2.10.0"
echo $tag
docker build -t ansible:$tag .
docker tag ansible:$tag ansible:latest
cp ./scripts/ah* /usr/local/bin/
chmod +x /usr/local/bin/*