#!/usr/bin/bash

# simple installer script, to build the ansible image and copy some scripts to /usr/local/bin

docker build -t ansible:2.9.0 .
docker tag ansible:2.9.0 ansible:latest
cp ./scripts/ah* /usr/local/bin/
chmod +x /usr/local/bin/*