#!/usr/bin/bash

docker_img="brtlvrs/ansible-helper:latest"

docker run --rm -name ah-$RANDOM -it \
  -v ~/.ssh/id_rsa:/root/.ssh/id_rsa \
  -v ~/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub \
  -v $(pwd):/ansible/playbooks \
  -v /var/log/ansible/ansible.log \
  $docker_img "$@"
