#!/usr/bin/env bash

docker_img="ansible:latest"

docker run --rm -it --name ah-playbook-$RANDOM \
  -v ~/.ssh/id_rsa:/root/.ssh/id_rsa \
  -v ~/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub \
  -v $(pwd):/ansible/playbooks \
  -v /var/log/ansible/ansible.log \
  $docker_img ansible-playbook "$@"